services:
  - type: web
    name: qanoonai-backend
    runtime: python
    plan: free
    rootDir: qanoonai-backend/qanoonai-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: web
    name: qanoonai-chatbot
    runtime: python
    plan: starter
    rootDir: Version 2/Chatbot
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
